---

- name: Docker-Minimal | Debian | Install Docker's dependencies
  ansible.builtin.apt:
    name: "{{ DOCKER_HC.dependencies }}"
    state: present

- name: Docker-Minimal | Debian | Download repo public-key
  ansible.builtin.get_url:
    url: "{{ DOCKER_HC.repo.pub_url }}"
    dest: "{{ DOCKER_HC.repo.pub_file }}_armored"
    checksum: "{{ DOCKER_HC.repo.pub_hash }}"
  register: dok_pub_dl

- name: Docker-Minimal | Debian | Adding repo public-key
  ansible.builtin.shell:  "gpg --dearmor <  {{ DOCKER_HC.repo.pub_file }}_armored > {{ DOCKER_HC.repo.pub_file }}"
  no_log: true
  when: dok_pub_dl.changed

- name: Docker-Minimal | Debian | Add docker repository
  ansible.builtin.apt_repository:
    repo: "{{ DOCKER_HC.repo.source }}"
    filename: 'docker'

- name: Docker-Minimal | Debian | Installing docker client
  ansible.builtin.apt:
    name: "{{ DOCKER_HC.packages.client }}"
    state: present
    update_cache: true

- name: Docker-Minimal | Debian | Installing docker server
  ansible.builtin.apt:
    name: "{{ DOCKER_HC.packages.server }}"
    state: present
  when: CONFIG_DOCKER.server

- name: Docker-Minimal | Debian | Configuring docker to listen on tcp (1/3)
  ansible.builtin.file:
    path: '/etc/systemd/system/docker.service.d'
    state: directory
    owner: 'root'
    group: 'root'
    mode: 0755
  when: CONFIG_DOCKER.listen_tcp.enable

- name: Docker-Minimal | Debian | Configuring docker to listen on tcp (2/3)
  ansible.builtin.copy:
    content: |
      # ansible_managed
      # ansibleguy.infra_docker_minimal

      [Service]
      ExecStart=
      ExecStart=/usr/bin/dockerd

    dest: '/etc/systemd/system/docker.service.d/override.conf'
    owner: 'root'
    group: 'root'
    mode: 0755
  when: CONFIG_DOCKER.listen_tcp.enable

- name: Docker-Minimal | Debian | Configuring docker to listen on tcp (3/3)
  ansible.builtin.template:
    src: 'templates/etc/docker/daemon.json.j2'
    dest: '/etc/docker/daemon.json'
    owner: 'root'
    group: 'root'
    mode: 0755
  when: CONFIG_DOCKER.listen_tcp.enable

- name: Docker-Minimal | Debian | Restarting docker
  ansible.builtin.systemd:
    name: 'docker.service'
    state: restarted
    daemon_reload: yes
  when: CONFIG_DOCKER.listen_tcp.enable

- name: Docker-Minimal | Debian | Downloading docker-compose
  ansible.builtin.get_url:
    url: "{{ DOCKER_HC.compose_url }}"
    dest: '/usr/local/bin/docker-compose'
    mode: 0755
  when: CONFIG_DOCKER.compose

- name: Docker-Minimal | Debian | Linking docker-compose
  ansible.builtin.file:
    path: '/usr/bin/docker-compose'
    src: '/usr/local/bin/docker-compose'
    state: link
  when: CONFIG_DOCKER.compose

- name: Docker-Minimal | Debian | Enabling/Starting docker service
  ansible.builtin.systemd:
    name: 'docker.service'
    state: started
    enabled: yes
  when: CONFIG_DOCKER.server
