---

- name: Docker-Minimal | Debian | Install Docker's dependencies
  ansible.builtin.apt:
    name: "{{ setup.dependencies }}"

- name: Docker-Minimal | Debian | Adding gpg repo-key
  ansible.builtin.shell: "curl -fsSL {{ setup.repo_key_url }} |
  gpg --dearmor -o {{ setup.repo_key }}"
  args:
    creates: "{{ setup.repo_key }}"

- name: Docker-Minimal | Debian | Add docker repository
  ansible.builtin.apt_repository:
    repo: "{{ setup.repo }}"
    filename: 'docker.list'

- name: Docker-Minimal | Debian | Installing docker
  ansible.builtin.apt:
    name: "{{ setup.packages }}"

- name: Docker-Minimal | Debian | Downloading docker-compose
  ansible.builtin.get_url:
    url: "{{ setup.compose_url }}"
    dest: '/usr/local/bin/docker-compose'
    mode: 0755
  when: CONFIG.compose

- name: Docker-Minimal | Debian | Linking docker-compose
  ansible.builtin.file:
    path: '/usr/bin/docker-compose'
    src: '/usr/local/bin/docker-compose'
    state: link
  when: CONFIG.compose
