---

- name: Docker-Minimal | Debian | Install Docker's dependencies
  ansible.builtin.apt:
    name: "{{ DOCKER_HC.dependencies }}"
    state: present

- name: Docker-Minimal | Debian | Download repo public-key
  ansible.builtin.get_url:
    url: "{{ DOCKER_HC.repo.gpg.url }}"
    dest: "{{ DOCKER_HC.repo.gpg.file }}_armored"
    checksum: "{{ DOCKER_HC.repo.gpg.hash }}"
  register: dok_gpg_dl

- name: Docker-Minimal | Debian | Adding repo public-key
  ansible.builtin.shell: "gpg --dearmor <  {{ DOCKER_HC.repo.gpg.file }}_armored > {{ DOCKER_HC.repo.gpg.file }}"
  no_log: true
  when: dok_gpg_dl.changed

- name: Docker-Minimal | Debian | Add docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }} signed-by={{ DOCKER_HC.repo.gpg.file }}]
    https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ DOCKER_HC.repo.tag }}"
    filename: 'docker'

- name: Docker-Minimal | Debian | Installing docker client
  ansible.builtin.apt:
    name: "{{ DOCKER_HC.packages.client }}"
    state: present
    update_cache: true

- name: Docker-Minimal | Debian | Installing docker server
  ansible.builtin.apt:
    name: "{{ DOCKER_HC.packages.server }}"
    state: present
  when: DOCKER.server

- name: Docker-Minimal | Debian | Removing daemon.json
  ansible.builtin.file:
    path: '/etc/docker/daemon.json'
    state: absent

- name: Docker-Minimal | Debian | Configuring docker service (1/2)
  ansible.builtin.file:
    path: '/etc/systemd/system/docker.service.d'
    state: directory
    owner: 'root'
    group: 'root'
    mode: 0755

- name: Docker-Minimal | Debian | Configuring docker service (2/2)
  ansible.builtin.copy:
    content: |
      # ansible_managed
      # ansibleguy.infra_docker_minimal

      [Service]
      ExecStart=
      ExecStart={{ DOCKER_SVC_CMD }}
      {% if DOCKER.nftables.clean or DOCKER.nftables.reload %}
      ExecStartPost=/usr/bin/systemctl reload nftables.service
      {% endif %}

    dest: '/etc/systemd/system/docker.service.d/override.conf'
    owner: 'root'
    group: 'root'
    mode: 0755

- name: Docker-Minimal | Debian | Restarting docker
  ansible.builtin.systemd:
    name: 'docker.service'
    state: restarted
    daemon_reload: yes
  when: DOCKER.tcp.enable

- name: Docker-Minimal | Debian | Downloading docker-compose
  ansible.builtin.get_url:
    url: "{{ DOCKER_HC.compose_url }}"
    dest: '/usr/local/bin/docker-compose'
    mode: 0755
  when: DOCKER.compose.enable

- name: Docker-Minimal | Debian | Linking docker-compose
  ansible.builtin.file:
    path: '/usr/bin/docker-compose'
    src: '/usr/local/bin/docker-compose'
    state: link
  when: DOCKER.compose.enable

- name: Docker-Minimal | Debian | Enabling/Starting docker service
  ansible.builtin.systemd:
    name: 'docker.service'
    state: started
    enabled: yes
  when: DOCKER.server
