---

# todo: restart-handler on config-changes

- name: Docker-Minimal | Showing debug info - user provided config
  ansible.builtin.debug:
    var: docker
  when: debug | bool

- name: Docker-Minimal | Showing debug info - running config
  ansible.builtin.debug:
    var: DOCKER
  when: debug | bool

- name: Docker-Minimal | Processing debian config
  ansible.builtin.import_tasks: debian.yml
  when: "ansible_distribution | lower in ['debian', 'ubuntu']"
